[package]
name = "slint_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.4.1"
rand = "0.8.5"
int_cmp = "0.2.1"
cast = "0.3.0"

[build-dependencies]
slint-build = "1.4.1"
