import { Button } from "std-widgets.slint";

export global GameLogic {
    callback click_cell(int, string);
}

component Cell inherits Rectangle {
    in property <string> value;
    in property <int> index;

    x: mod(index, 4) * 110px + 10px;
    y: floor(index / 4) * 110px + 10px;
    width: 100px;
    height: 100px;
    background: value == "" ? #e0e0e0 : #a3ecea;
    border-radius: 5px;

    Text {
        text: value;
        font-weight: 900;
        font-size: 24px;
    }

    TouchArea {
        mouse-cursor: value == "" ? MouseCursor.default : MouseCursor.pointer;
        clicked => {
            GameLogic.click_cell(index, value)
        }
    }
}

export component MainWindow inherits Window {

    callback reset;

    in property <bool> win: false;
    in property <[int]> number_array;

    title: "Main Window";
    width: 450px;
    height: 550px;

    Button {
        y: 0;
        height: 50px;
        text: "reset";
        clicked => {
            root.reset();
        }
    }

    Rectangle {
        width: parent.width;
        height: 450px;
        y: 50px;
        background: #e0e0e0;
        for number[i] in number_array: Cell {
            value: number == -1 ? "" : number + "";
            index: i;
        }
    }

    if (win) : Text {
        y: 500px;
        height: 50px;
        text: "success";
    }
}